### ISSUE TITLE
Work without daemon?

### ISSUE THREAD

**Issue by renyuneyun** [XanClic/krunner-mpd#1]
I'm looking for a krunner plugin which can control mpd (without launching a GUI), and find this one.

The description says I need to launch a ruby program (as a daemon in fact) in order to make this plugin work.
But why is there a need for a daemon...? Shouldn't this intend to be only "controlling" the mpd, rather than "reporting" it, which means it doesn't need to be stateful (i.e. it should be stateless)?

**Comment by renyuneyun** [comment]
By the way, I'm willing to help, but I have no experience with krunner (well, also no experience with ruby...). What's the basics of developing krunner plugins?

p.s. I'm also archlinux user, and hope to see this package on aur :)

**Comment by XanClic** [comment]
As of commit b9ded33ffa0ac7145eea3d7007ac966ce0786ddf, krunner should launch the plugin automatically. I haven’t yet investigated whether it’s possible to not keep it in the background and instead always exit once a result has been returned (and then be reloaded once another query comes in), though.
But again, I’m not sure whether that's actually a good idea in the first place… So I guess I’m closing this issue for now…?

**Comment by XanClic** [comment]
Oh, and by the way, apart from the MPD and the DBus connection, the plugin actually is stateless (regarding the code). So it’s only a matter of exiting every time a response has been sent and modifying the .desktop file (and maybe the .service file?) to make krunner launch the service every time it’s needed.
I guess I’ll open a separate issue for that and probably look into that later (as a configure option).
